config/routes.rb
Dippam::Application.routes.draw do
  resources :summary_documents, :vmr_interviews, :eppi_lc_subjects, :ied_institutions
  resources :eppi_documents do
    resources :eppi_pages do
      get :download, on: :member
    end
  end
  resources :ied_records do 
    resources :ied_pages, :enclosures
  end
end

app/models/ied_record.rb
# IedRecord is the main document model of the IED collection.
#
# - IED Records are classified in categories.
# - IED Records have donated/belong to an institution.
# - IED Records may have one or more enclosures (attachments).
class IedRecord < ActiveRecord::Base
  # Associations
  belongs_to :ied_institution, foreign_key: :institution_id
  belongs_to :ied_category, foreign_key: :ied_chapter_id
  has_many :ied_enclosures
  has_one :summary_document, as: :source

  # SOLR indexing
  searchable do
    text :name, default_boost: 2, stored: true
    text :transcript, stored: true
    time :timestamp
    string :serial
    string :name
    integer :ied_chapter_id
    integer :num_images
  end
  
  # Accessor Methods
  def self.earliest; minimum(:timestamp).strftime('%Y-%m-%d'); end
  def self.latest; maximum(:timestamp).strftime('%Y-%m-%d'); end
  def num_images; ied_enclosures.size; end

  # Search customisations - preprocess query, send to SOLR, fetch results.
  def self.do_search params
    search do
      keywords params[:q], highlight: true if params[:q].size > 2
      with(:ied_chapter_id, params[:cat].keys) if params.key?(:cat) and not params[:cat].key?('0')
      order_by params[:sort], params[:sort_dir] if params.key? :sort_dir
      paginate page: params[:page], per_page: params[:per_page] if params.key? :page
      with(:timestamp).greater_than(Date.parse params[:start]) if params.key? :start
      #with(:timestamp).less_than(Date.parse params[:end]) if criteria.key? :end
      keywords ''
      facet :ied_chapter_id
    end
  end

  # Generate citation to be used when referring to this record.
  def citation
    str = name
    if institution_id == 530
      str += ' PRONI '
      m = source.match /(T|D\.*\ *\d+\/*\d*)/
      str += m[1] unless m.nil?
    end
    "#{str} CMSIED  #{serial}"
  end
end

app/controllers/ied_records_controller.rb
class IedRecordsController < ApplicationController
  def index
    params ||= { q: '', page: 1, sort: 'timestamp',
                 cat: {'0' => 'on'}, sort_dir: :asc, 
                 #start: "1/1/#{IedRecord.earliest.year}", 
                 #end: "31/12/#{IedRecord.latest.year}", 
                 page: 1, per_page: 15, exact: true
    }
    @results = IedRecord.do_search params
    @facets  = IedCategory.where('ied_categories.show = ?', true).order(:name)

    respond_to  do |f|
      f.html
      f.results
      f.facets
    end
  end

  def show
    @record = IedRecord.find params[:id]
    @hits = IedRecord.do_search(params.merge({ page: 1, per_page: 1000 })).hits.map(&:primary_key)
    @position = @hits.index @record.id.to_s
    
    render 'transcript' if request.url.match /\.transcript$/
  end
end

app/helpers/ied_records_helper.rb
module IedRecordsHelper
  def highlight(text, phrases, *args)
    unless phrases.nil?
      m = phrases.match(/\"(.+)\"/) 
      phrases = m.nil? ? phrases.scan(/\w+/) : m[1]
    end
    super
  end
end

app/views/ied_records/index.html.haml
%form
  = render partial: 'shared/search'
  %fieldset.time
    %legend Date Range
    = label_tag :start, 'Start'
    = text_field_tag :start, params[:start]
    = label_tag :end, 'End'
    = text_field_tag :end, params[:end]
  = render partial: 'shared/facets', locals: { collection: @facets, name: :cat, facet: params[:cat] }
  = hidden_field_tag :sort, :timestamp
  = hidden_field_tag :sort_dir, :asc

%table
  %thead
    %tr
      %th Date
      %th Title
      %th Type
  %tbody
    - @results.each_hit_with_result do |hit, r|
      %tr
        %td
          - unless r.timestamp.nil?
            = r.timestamp.strftime('%d-%m-%Y') 
        %td= link_to highlight(r.name, params[:q]), r
        %td= # link_to r.category.name, r.category

app/views/ied_records/show.html.haml
- title highlight(@record.name, params['q'] )

#toolbar
  = link_to 'PDF', @record, format: :pdf
  = link_to 'Transcript', @record, format: :transcript
  .pagination      
    - unless @position.nil?
      = "#{@position + 1} of #{@hits.size}"
      - unless @position == 0
        = link_to 'Previous', ied_record_url(@hits[@position - 1])
      - unless @position == @hits.size - 1
        = link_to 'Next', ied_record_url(@hits[@position + 1])

%table
  %tbody
    %tr
      %td.docid Document ID
      %td= @record.serial 
    %tr
      %td.date Date
      %td= @record.timestamp.strftime("%d-%m-%Y")
    %tr
      %td.type Document Type
      %td= link_to @record.category.name, @record.category
    %tr
      %td.archive Archive
      %td= link_to @record.institution.name, @record.institution
    - if @record.institution.name != 'Private Donor'
      %tr
        %td.source Source
        %td= @record.source
    %tr
      %td.citation Citation
      %td= @record.citation
      
  %pre.transcript
    != highlight @record.transcript.force_encoding("ISO-8859-1"), params[:q] 

- unless @record.ied_enclosures.empty?
  - for e in @record.ied_enclosures
    .thumbnail
      = image_tag e.image(:thumb), size: '100x100', alt: e.label
      %p= e.label

app/views/ied_records/show.txt.haml
= raw @record.transcript