config/routes.rb
Dippam::Application.routes.draw do
  resources :summary_documents, :vmr_interviews, :eppi_lc_subjects, :ied_institutions
  resources :eppi_documents do
    resources :eppi_pages do
      get :download, on: :member
    end
  end
  resources :ied_records do 
    resources :ied_pages, :enclosures
  end
end

app/models/summary_document.rb
class SummaryDocument < ActiveRecord::Base
  belongs_to :source, polymorphic: true
  before_save :save_title
  before_create :save_title
  
  searchable do
    string :title, stored: true
    text :body, stored: true
  end

  def self.do_search criteria
    search do
      keywords criteria['q'], highlight: true unless criteria['q'].size < 3
      paginate page: criteria['page'], per_page: 20
    end
  end

  def body
    case source_type
    when 'EppiDocument' then source.content
    when 'IedRecord' then source.transcript
    else source.content
    end
  end

  def save_title
    self.title = (self.source_type == 'EppiDocument') ? 
      self.source.eppi_breviate.title : self.source.name
  end
end

app/controllers/summary_documents_controller.rb
class SummaryDocumentsController < ApplicationController
  def index
    params ||= { q: '', page: 1, sort: :title, sort_dir: :asc, per_page: 15 }
    @results = SummaryDocument.do_search params
    
    respond_to do |f|
      f.html
      f.results
    end
  end

  def show
    @record = IedRecord.find params[:id]
    @results = IedRecord.do_search params.merge({ per_page: 1000, page: 1 })
    @position = @results.results.index @record
  end
  
  def edit
    @record = Ied::Record.find params[:id]
  end
end

app/views/summary_documents/index.html.haml
%form
  = render partial: 'shared/pagination'
  %fieldset
    = text_field_tag :qclean, params[:q]
    = text_field_tag :qclean, params[:q]
    = submit_tag 'Search'
    = hidden_field_tag :sort, :timestamp
    = hidden_field_tag :sort_dir, :asc

%table
  %thead
    %tr
      %th Title
      %th Year
      %th Type
  %tbody
    - @results.each_hit_with_result do |hit, r|
      - year = ''
      - year = r.source.timestamp.year if r.source.class == IedRecord and r.source.timestamp.present?
      - year = r.source.session if r.source.class == EppiDocument      
      %tr
        %td= link_to highlight(r.save_title, params[:q]), record_url(r.source)          
        %td= year
        %td= r.source.class

app/views/summary_documents/show.html.haml
- title highlight(@record.name, params[:q])

.pagination      
  - unless @results.results.nil?
    %span= "#{@position + 1} of #{@results.results.size}"
  - unless @position.nil?
    - unless @position == 0
      = link_to 'Previous', record_url(@results.results[@position - 1])
    - unless @position == @results.results.size - 1
      = link_to 'Next', record_url(@results.results[@position + 1])

%dl
  %dt Document ID
  %dd= @record.serial 
  %dt Date
  %dd= @record.timestamp.strftime("%d-%m-%Y")
  %dt Document Type
  %dd= link_to @record.category.name, @record.category
  %dt Archive
  %dd= link_to @record.institution.name, @record.institution
  %dt Citation
  %dd= @record.citation

#transcript
  %pre= highlight @record.transcript.force_encoding('ISO-8859-1'), params[:q] 

- if @record.ied_enclosures.size > 0 
  = render partial: :enclosures