config/routes.rb
Dippam::Application.routes.draw do
  resources :summary_documents, :vmr_interviews, :eppi_lc_subjects, :ied_institutions
  resources :eppi_documents do
    resources :eppi_pages do
      get :download, on: :member
    end
  end
  resources :ied_records do 
    resources :ied_pages, :enclosures
  end
end

app/models/eppi_document.rb
# An EppiDocument is the core model of the EPPI collection,
# representing an individual document that contains 1+ pages.
#
# - EPPI documents are published in breviates.
# - EPPI documents may be part of a session.
#
# There are four types of EPPI document in the collection:
#
# 1. Account
# 1. Bill
# 1. Command Paper
# 1. Report
#
class EppiDocument < ActiveRecord::Base
  # Associations
  has_many   :eppi_pages
  has_one :summary_document, as: :source
  belongs_to :eppi_lc_subject
  belongs_to :eppi_doctype
  belongs_to :eppi_breviate
  belongs_to :eppi_session

  # Sunspot Indexing
  searchable do
    text :title_actual, stored: true
    string :title_actual
    string :published
    string :session
    text :content
    string :code
    string :source
    integer :eppi_doctype_id
    string :paper_no
    integer :num_pages
  end

  # Preprocess search query and send to SOLR, returning results.
  def self.do_search params
    search do
      if params[:qclean].size == 0 then
        case params[:fields]
        when 'titles' then keywords params[:qclean], fields: :title_actual
        when 'code' then with(:code).starting_with params[:qclean].upcase
        when 'exact_title' then with(:title_actual).starting_with params[:qclean]
        when 'paper_no' then with(:paper_no).starting_with params[:qclean]
        else keywords params[:q]
        end 
      end
      
      with(:session).greater_than params[:from] if params[:from].present?
      with(:session).less_than params[:to] if params[:to].present?
      with(:eppi_doctype_id, params[:cat].keys) unless params[:cat].key? '0'
      order_by params[:sort], params[:sort_dir]
      paginate page: params[:page], per_page: params[:per_page]
      facet :session
      facet :eppi_doctype_id
    end
  end

  # Accessor Methods
  def num_pages; eppi_pages.size; end
  def content; eppi_pages.map(&:content).join; end
  def title; eppi_breviate.title; end

  # Return the document code.
  # Code formats vary over the years and also on source.
  def code
    # Short circuit is this isn't a Command Paper.
    return "#{source} #{session} (#{paper_no}) #{vol} #{start_page}" if source != 'CMD'

    # Paper number prefixes are different for sessions.
    prefix = case session[0..3].to_i
      when 1000..1869 then ''
      when 1870..1899 then 'C.'
      when 1900..1919 then 'Cd.'
      else 'Cmd.'
    end
    
    "HC #{session} [#{prefix}#{paper_no}] #{vol} #{start_page}"
  end

  # Return a URI where the associated PDF can be accessed.
  def pdf_location
    "/pdf/#{authoritative_ref}.pdf" if File.exists? "public/pdf1/#{authoritative_ref}.pdf"
  end

  # Return the volume year in roman numerals.
  def vol_roman
    dict = { M: 1000, CM: 900, D: 500, CD: 400,
             C: 100,  XC: 90,  L: 50,  XL: 40,
             X: 10 ,  IX: 9,   V: 5,   IV: 4,
             I: 1 };
    input, output = vol.to_i, ''

    # Descend through the character list.
    dict.each_pair do |r, a|
      # Subtract from the input/add to the output until
      # this character is no longer useful.
      while input >= a { input -= a; output << r.to_s }
    end
    
    output
  end
end
end

app/controllers/eppi_documents_controller.rb
class EppiDocumentsController < ApplicationController
  def index
    params ||= { q: '', qclean: '', page: 1, sort: :title_actual,
                 sort_dir: :asc, cat: { '0' => 'on' }, fields: :titles }

    # Override sort when chronologic checkbox ticked.
    params.merge!({ sort: :session, sort_dir: :asc}) if params[:chrono].present?

    @results = EppiDocument.do_search params
    @doctypes = EppiDoctype.order :name
    
    respond_to do |f|
      f.html
      f.results
      f.facets
      f.json { render json: @results }
    end
  end

  def show
    q = params[:q] || ''
    @document = EppiDocument.find params[:id]
    @results = EppiPage.search do
      keywords q { highlight :content }
      with :eppi_document_id, params[:id]
    end

    respond_to do |f|
      f.html
      f.txt
    end
  end
end

app/views/eppi_documents/index.html.haml
%form
  = render partial: 'shared/search'
  %fieldset.fields
    %legend Search Type
    - values = %w[fulltext titles exact_title code paper_no]
    - names  = ['Fulltext', 'Titles', 'Exact Title', 'Command No', 'Paper No']
    - values.each_with_index do |v, i|
      = radio_button 'search', 'fields', v, id: v, checked: v == params[:fields]
      %label{ for: v }= names[i]
  %fieldset.time
    %legend Date Range
    = label_tag :chrono, 'Order Chronologically'
    = text_field_tag :from, params[:from] || EppiSession.earliest
    = text_field_tag :to, params[:to] || '1922'
    = check_box_tag :chrono, checked: true
  = render partial: 'shared/facets', locals: { collection: @doctypes, name: :cat, facet: params[:cat] }
  = hidden_field_tag :sort, :title
  = hidden_field_tag :sort_dir, :asc
%table
  %thead
    %tr
      %th Code
      %th Breviate Title
      %th Session
      %th Pages
  %tbody
    - @results.each_hit_with_result do |hit, r|
      %tr
        %td= link_to r.code, r
        %td= #link_to highlight(r.eppi_breviate.title_actual, params[:q]), r
        %td= #r.eppi_session.name 
        %td= r.eppi_pages.size

app/views/eppi_documents/show.html.haml
- title @document.eppi_breviate.title

#toolbar
  = link_to "Results for '#{params[:q]}'", eppi_documents_url
  = link_to 'PDF', @document.pdf_location
  = link_to 'Transcript', @document, format: :txt
  %form
    = label_tag :q, 'Search within'
    = text_field_tag :q
    = submit_tag 'Go'
  .pagination
    %span.info= "#{@document.eppi_pages.size} Pages"
    = link_to 'View', [@document, @document.eppi_pages.first]

#metadata
  %h2 Document Metadata
  = link_to 'Open Document', [@document, @document.eppi_pages.first]
  %dl
    %dt Source
    %dd= @document.source
    %dt Paper No
    %dd= @document.paper_no
    - if @document.title_actual.present?
      %dt Title Actual
      %dd= @document.title_actual
    - if @document.corp_authors.present?
      %dt Corp Authors
      %dd= @document.corp_authors
    %dt LC Subject Heading
    %dd= @document.eppi_lc_subject.full_name
    %dt Breviate Keywords
    %dd= @document.eppi_breviate.keywords
    - if @document.personal_author.present?
      %dt Personal Author
      %dd= @document.personal_author
    - if @document.publisher.present?
      %dt Publisher
      %dd= @document.publisher
    - unless @document.eppi_breviate.eppi_volume.nil?
      %dt Breviate Volume
      %dd= @document.eppi_breviate.eppi_volume.name
    %dt Breviate Page
    %dd= @document.breviate_page
    - if @document.tables.present?
      %dt Tables
      %dd= @document.tables
    - if @document.series.present?
      %dt Series
      %dd= @document.series
    - if @document.chairman.present?
      %dt Chairman
      %dd= @document.chairman
    - if @document.abstract.present?
      %dt Abstract
      %dd= @document.abstract
    - if @document.pages_sectioned.present?
      %dt Pages Sectioned
      %dd= @document.pages_sectioned
    - if @document.held_by.present?
      %dt Held By
      %dd= @document.held_by
    - if @document.additional_components.present?
      %dt Additional Components
      %dd= @document.additional_components
    %dt Start Page
    %dd= @document.start_page
    %dt Volume
    %dd= @document.vol
    %dt Sub Volume
    %dd= @document.subvol_arabic
    %dt Session
    %dd= @document.eppi_session.name
    - if @document.published.present?
      %dt Published
      %dd= @document.published
    - if @document.appointed.present?
      %dt Appointed
      %dd= @document.appointed

#hits
  %h2 Hits
  %p
    %em Term
    %span.highlight= params[:q]
  %h3 View Matched Pages
  %ul
    - @results.each_hit_with_result do |h, d|
      %li
        %span.page= link_to "Page #{d.ordinal + 1}", [@document, d]
        - h.highlights(:content).each do |j|
          - s = raw j.format {|w| w}
          %p= link_to highlight(s, params[:qclean]), [@document, d]

app/views/eppi_documents/show.txt.haml
= raw @document.eppi_pages.map(&:content).join("\n")